name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install ruff

      - name: Ruff check
        run: ruff check .

  # (Opcional) "build seco": garante que os módulos importam
  import-smoke-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Import modules (smoke test)
        run: |
          python - << 'PY'
          import importlib
          modules = [
            "etl.common.config",
            "etl.common.dateutils",
            "etl.inpe.fetch_fires",
            "etl.weather.fetch_weather",
            "etl.ibge.load_ref_municipios",
            "etl.gold.export_parquet",
          ]
          for m in modules:
              importlib.import_module(m)
              print("[ok]", m)
          PY
